title: Minimal
tagline:
  Minimal project theme for Jekyll

google_analytics: UA-86544704-1
google_adsense: ca-pub-3538270718430385:3984415626

repository: hasharray/minimal
gems:
  - jekyll-mentions
  - jekyll-github-metadata
